# Generated by Django 3.2 on 2024-07-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fechaCreacion',
            field=models.DateTimeField(),
        ),
    ]
