# Generated by Django 3.2 on 2024-07-04 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appEventos', '0002_alter_eventos_fechacreacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='participantes',
            field=models.ManyToManyField(related_name='eventos_participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
