# Generated by Django 3.2 on 2024-07-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEventos', '0003_eventos_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='participantes',
        ),
    ]
